<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * 부산 맛집 샘플 데이터 20건 삽입
 * 실행: php spark db:seed RestaurantSeeder
 */
class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        // category_num: 1=한식 2=일식 3=중식 4=양식 5=분식/간식 6=카페/디저트 7=뷔페 8=기타
        // price_range : 1=₩(1만원미만) 2=₩₩(1~3만원) 3=₩₩₩(3만원이상)
        $rows = [
            [
                'name'         => '원조 할매 돼지국밥',
                'category_num' => 1,
                'price_range'  => 1,
                'info'         => '50년 전통의 부산 서면 돼지국밥 원조 맛집. 진하고 구수한 국물이 일품입니다.',
                'address1'     => '부산광역시 부산진구 서면로 12',
                'phone'        => '051-123-1001',
                'sido'         => '부산광역시',
                'open_time'    => '06:00~21:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '해운대 암소갈비집',
                'category_num' => 1,
                'price_range'  => 3,
                'info'         => '해운대 해변 인근 프리미엄 한우 암소갈비 전문점. 생갈비와 LA갈비가 유명합니다.',
                'address1'     => '부산광역시 해운대구 해운대해변로 264',
                'phone'        => '051-123-1002',
                'sido'         => '부산광역시',
                'open_time'    => '11:00~22:00',
                'parking'      => 1,
                'state'        => 1,
            ],
            [
                'name'         => '광안리 조개구이 바다',
                'category_num' => 1,
                'price_range'  => 2,
                'info'         => '광안대교 야경을 보며 즐기는 싱싱한 조개구이. 바지락, 소라, 전복 등 다양한 해산물.',
                'address1'     => '부산광역시 수영구 광안해변로 219',
                'phone'        => '051-123-1003',
                'sido'         => '부산광역시',
                'open_time'    => '15:00~23:30',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '남포동 씨앗호떡 본점',
                'category_num' => 5,
                'price_range'  => 1,
                'info'         => '부산 남포동 BIFF광장 대표 길거리 음식. 고소한 씨앗이 가득한 달콤한 호떡.',
                'address1'     => '부산광역시 중구 BIFF광장로 21',
                'phone'        => '051-123-1004',
                'sido'         => '부산광역시',
                'open_time'    => '10:00~22:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '스시 오마카세 하루',
                'category_num' => 2,
                'price_range'  => 3,
                'info'         => '해운대 프리미엄 일식 오마카세. 매일 공수되는 신선한 제철 생선으로 구성.',
                'address1'     => '부산광역시 해운대구 달맞이길 62번길 14',
                'phone'        => '051-123-1005',
                'sido'         => '부산광역시',
                'open_time'    => '12:00~22:00',
                'parking'      => 1,
                'state'        => 1,
            ],
            [
                'name'         => '카페 선셋 해운대',
                'category_num' => 6,
                'price_range'  => 2,
                'info'         => '해운대 해변이 보이는 오션뷰 카페. 수제 디저트와 스페셜티 커피를 즐길 수 있습니다.',
                'address1'     => '부산광역시 해운대구 해운대해변로 120',
                'phone'        => '051-123-1006',
                'sido'         => '부산광역시',
                'open_time'    => '09:00~22:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '기장 대게 직판장',
                'category_num' => 1,
                'price_range'  => 3,
                'info'         => '기장 앞바다에서 갓 잡은 싱싱한 대게와 킹크랩을 합리적인 가격에 제공합니다.',
                'address1'     => '부산광역시 기장군 기장읍 연화리 12',
                'phone'        => '051-123-1007',
                'sido'         => '부산광역시',
                'open_time'    => '10:00~21:00',
                'parking'      => 1,
                'state'        => 1,
            ],
            [
                'name'         => '동래 할매파전',
                'category_num' => 5,
                'price_range'  => 1,
                'info'         => '동래 파전 골목의 대표 맛집. 바삭하고 쫄깃한 파전에 막걸리 한 잔이 일품.',
                'address1'     => '부산광역시 동래구 온천장로 95',
                'phone'        => '051-123-1008',
                'sido'         => '부산광역시',
                'open_time'    => '11:00~21:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '브루어리 버거 해운대',
                'category_num' => 4,
                'price_range'  => 2,
                'info'         => '수제 패티와 브루어리 맥주를 함께 즐길 수 있는 해운대 핫플. 두툼한 수제버거가 인기.',
                'address1'     => '부산광역시 해운대구 중동1로 56',
                'phone'        => '051-123-1009',
                'sido'         => '부산광역시',
                'open_time'    => '11:30~22:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '홍보각 중화요리',
                'category_num' => 3,
                'price_range'  => 2,
                'info'         => '서면 30년 전통 중화요리 전문점. 짬뽕, 탕수육, 코스 요리 모두 인기 메뉴.',
                'address1'     => '부산광역시 부산진구 서면문화로 20',
                'phone'        => '051-123-1010',
                'sido'         => '부산광역시',
                'open_time'    => '11:00~21:30',
                'parking'      => 1,
                'state'        => 1,
            ],
            [
                'name'         => '부산역 원조 밀면',
                'category_num' => 1,
                'price_range'  => 1,
                'info'         => '부산 대표 향토 음식 밀면의 원조. 쫄깃한 면발과 시원한 육수가 특징.',
                'address1'     => '부산광역시 동구 중앙대로 196',
                'phone'        => '051-123-1011',
                'sido'         => '부산광역시',
                'open_time'    => '10:00~20:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '그랜드 뷔페 센텀',
                'category_num' => 7,
                'price_range'  => 3,
                'info'         => '센텀시티 프리미엄 뷔페. 해산물, 스테이크, 스시, 디저트 등 200여 가지 메뉴.',
                'address1'     => '부산광역시 해운대구 센텀남대로 35',
                'phone'        => '051-123-1012',
                'sido'         => '부산광역시',
                'open_time'    => '11:30~22:00',
                'parking'      => 1,
                'state'        => 1,
            ],
            [
                'name'         => '나폴리 피자 광안리',
                'category_num' => 4,
                'price_range'  => 2,
                'info'         => '나폴리 정통 방식의 화덕 피자 전문점. 모짜렐라 마르게리타와 트러플 피자가 인기.',
                'address1'     => '부산광역시 수영구 광안해변로 57',
                'phone'        => '051-123-1013',
                'sido'         => '부산광역시',
                'open_time'    => '11:00~22:30',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '초량 이바구 분식',
                'category_num' => 5,
                'price_range'  => 1,
                'info'         => '초량 이바구길 골목 분식 맛집. 떡볶이, 순대, 어묵이 조합된 모듬이 인기.',
                'address1'     => '부산광역시 동구 초량상로 77',
                'phone'        => '051-123-1014',
                'sido'         => '부산광역시',
                'open_time'    => '10:00~19:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '남포동 통닭 골목 원조',
                'category_num' => 1,
                'price_range'  => 1,
                'info'         => '남포동 통닭 골목의 60년 전통 바삭 통닭집. 옛날 방식 그대로의 바삭한 튀김옷.',
                'address1'     => '부산광역시 중구 광복로 51',
                'phone'        => '051-123-1015',
                'sido'         => '부산광역시',
                'open_time'    => '11:00~21:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '기장 멸치쌈밥 정식',
                'category_num' => 1,
                'price_range'  => 2,
                'info'         => '기장 앞바다 멸치로 만든 쌈밥 정식 전문점. 멸치회, 멸치쌈밥, 멸치조림 코스.',
                'address1'     => '부산광역시 기장군 기장읍 차성로 262',
                'phone'        => '051-123-1016',
                'sido'         => '부산광역시',
                'open_time'    => '10:30~20:30',
                'parking'      => 1,
                'state'        => 1,
            ],
            [
                'name'         => '비스트로 수영',
                'category_num' => 4,
                'price_range'  => 3,
                'info'         => '수영구 감성 이탈리안 레스토랑. 파스타, 리조또, 와인 페어링 코스 전문.',
                'address1'     => '부산광역시 수영구 수영로 365',
                'phone'        => '051-123-1017',
                'sido'         => '부산광역시',
                'open_time'    => '11:30~21:30',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '해운대 낙지볶음 명가',
                'category_num' => 1,
                'price_range'  => 2,
                'info'         => '해운대 현지인 단골 낙지볶음 맛집. 산낙지와 볶음 낙지 모두 당일 직접 공수.',
                'address1'     => '부산광역시 해운대구 구남로 21',
                'phone'        => '051-123-1018',
                'sido'         => '부산광역시',
                'open_time'    => '11:00~22:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '라멘 타로 서면',
                'category_num' => 2,
                'price_range'  => 2,
                'info'         => '일본 정통 돈코츠 라멘 전문점. 12시간 우려낸 진한 돈코츠 국물이 자랑.',
                'address1'     => '부산광역시 부산진구 서면로 46',
                'phone'        => '051-123-1019',
                'sido'         => '부산광역시',
                'open_time'    => '11:00~23:00',
                'parking'      => 0,
                'state'        => 1,
            ],
            [
                'name'         => '브루클린 로스터리 광복',
                'category_num' => 6,
                'price_range'  => 2,
                'info'         => '광복동 감성 스페셜티 커피 로스터리. 직접 로스팅한 원두와 시그니처 라떼 아트.',
                'address1'     => '부산광역시 중구 광복로 68',
                'phone'        => '051-123-1020',
                'sido'         => '부산광역시',
                'open_time'    => '09:00~21:00',
                'parking'      => 0,
                'state'        => 1,
            ],
        ];

        $now = date('Y-m-d H:i:s');

        foreach ($rows as $i => $row) {
            $this->db->table('busan_restaurant')->insert(array_merge($row, [
                'star_point' => 0,
                'view_cnt'   => rand(10, 500),
                'like_cnt'   => rand(0, 100),
                'reg_id'     => 'admin',
                'reg_date'   => date('Y-m-d H:i:s', strtotime($now) - (20 - $i) * 86400),
                'edit_date'  => $now,
            ]));
        }

        echo "✅ 맛집 샘플 데이터 20건 삽입 완료\n";
    }
}
